# Generated by Django 5.0.3 on 2024-05-21 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educationaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='Default Degree', max_length=50)),
                ('specification', models.CharField(default='Default Specification', max_length=50)),
                ('college', models.CharField(default='Default College', max_length=50)),
                ('passout_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Financialdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('aadhaar_number', models.IntegerField()),
                ('pan_number', models.CharField(default='Default Pan', max_length=50)),
                ('phonepe_id', models.CharField(default='Default Phonepe', max_length=50)),
                ('googlepay_id', models.CharField(default='Default Googlepay', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicaldetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='user',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='fullname',
            field=models.CharField(default='Default Fullname', max_length=50),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(default='undisclosed', max_length=50),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='address',
            field=models.CharField(default='Default Address', max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='pin',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.DeleteModel(
            name='MedicalDetails',
        ),
    ]
