# Generated by Django 5.0.3 on 2024-05-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_professionaldetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='dob',
            field=models.DateTimeField(default=0),
        ),
    ]
