# Generated by Django 5.0.3 on 2024-05-23 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_personaldetails_dob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaldetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionaldetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Medicaldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thyroid', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Default thyroid', max_length=6)),
                ('asthma', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Default asthma', max_length=6)),
                ('allergy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Default allergy', max_length=6)),
                ('diabetics', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Default diabetic', max_length=6)),
                ('bp', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Default bp', max_length=6)),
                ('cholestrol', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Default cholestrol', max_length=6)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
