# Generated by Django 5.0.3 on 2024-05-24 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_educationaldetails_user_financialdetails_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldetails',
            name='bp',
        ),
        migrations.AddField(
            model_name='medicaldetails',
            name='bloodpressure',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=6),
        ),
        migrations.AddField(
            model_name='medicaldetails',
            name='heartdisease',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=6),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='allergy',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=6),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='asthma',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=6),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='cholestrol',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=6),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='diabetics',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=6),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='thyroid',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=6),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
