# Generated by Django 5.0.3 on 2024-05-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_medicaldetails_bp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdetails',
            name='expense_amount2',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='expense_item2',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='income_amount2',
        ),
        migrations.RemoveField(
            model_name='financialdetails',
            name='income_item2',
        ),
    ]
